version: "3"

volumes:
  cinema-data:

services:
  mysql:
    image: "mysql:5.7.23"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=cinema
    volumes:
      - cinema-data:/var/lib/mysql