swagger: "2.0"

info:
  title: Cinema API
  description: API to perform edition regarding prices, show times and ratings about fast and furious movies in a small cinema.
  version: 1.0.0

host: localhost:9000

schemes:
  - http
